### ISSUE TITLE
Allow a child node to be re-linked to another parent node

### ISSUE THREAD

**Issue by cluxter** [Mindmapp/mindmapp#23]
# Current behaviour
We can't modify the link between a parent node and a child node. Thus every time we need to affect some child nodes to another parent node, we must delete them all and re-create them one by one. This makes the tool of very limited use.
# Expected behaviour
The link between two nodes can be modified to be affected to some other node.

**Comment by cedoor** [comment]
Hello @cluxter,

this is an interesting [mmp](https://github.com/Mindmapp/mmp) library feature. However, it has already been planned the possibility to copy and paste a node [#2](https://github.com/Mindmapp/mmp/issues/2).
For the moment I hope I can finish this.

In any case, I leave the issue open for future implementations, thanks!
