### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by Prathik-Jain** [Mindmapp/mindmapp#29]
I get an error when I `npm start` while `npm run ng:build` is running

It works fine when I build the app and then `npm start` but then it doesn't auto reload.

**Comment by cedoor** [comment]
Hi @Prathik-Jain,

for now it is necessary to run `ng:build` and `start` scripts in order, separately, and to wait the angular build completion. Have you run `start` script only after the angular build completion?

**Comment by Prathik-Jain** [comment]
@cedoor  yes!

**Comment by cedoor** [comment]
What is the error? What are the versions of npm and node?

**Comment by Prathik-Jain** [comment]
Surprisingly, I worked today.
Sorry @cedoor

**Comment by Prathik-Jain** [comment]
Found out what was causing the problem..
We get the error when we already have two instances `npm run build` be it the same app or another.

**Comment by cedoor** [comment]
Good @Prathik-Jain, in this case it is a normal behavior.
Thank you!
