### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hubitor** [Mindmapp/mindmapp#36]
I get following error when I try to install mindmapp:
```
$ chmod a+x Mindmapp-0.7.9.AppImage
$ ./Mindmapp-0.7.9.AppImage                                                                                                                              
[1]    15528 segmentation fault (core dumped)  ./Mindmapp-0.7.9.AppImage
```

**Comment by cedoor** [comment]
Hello @hubitor, I don't get this error. 
Can you give me more informations about OS?
Have you tried the new version 0.7.10? Do you get the same error?

**Comment by hubitor** [comment]
Hello @cedoor,

> Can you give me more informations about OS?

Arch Linux

> Have you tried the new version 0.7.10? Do you get the same error?

Just did. The same error.

**Comment by cedoor** [comment]
Hello @hubitor. Yes, open a new issue!

Thanks for this fix! Soon I try the application directly on Archlinux.
