### ISSUE TITLE
Add possibility to auto color

### ISSUE THREAD

**Issue by liberodark** [Mindmapp/mindmapp#38]
Hi,

Please add option for auto color branch.

Cordialy

**Comment by cedoor** [comment]
Hello @liberodark, 
can you explain better how this feature works?

Thanks.

**Comment by liberodark** [comment]
Yes look : https://framindmap.org/mindmaps/index.html

**Comment by cedoor** [comment]
It's clear. I add this feature to Mindmapp project dashboard!

Thank you!

**Comment by liberodark** [comment]
Please make this feature in settings not obligatory.
Possibility to on/off is better for users.
Thanks

**Comment by cedoor** [comment]
Yes, I want to implement it in this way.

Thank you!
