### ISSUE TITLE
Add possibility to open .mmap

### ISSUE THREAD

**Issue by liberodark** [Mindmapp/mindmapp#39]
Hi,

Please add possibility to open your .mmap file with your software.

Cordialy

**Comment by cedoor** [comment]
Hello @liberodark, this is a good issue. 
I'm studying how to work the field `fileAssociations` of Electron builder.
Soon I will do some tests!

Thank you very much.

**Comment by liberodark** [comment]
Yeah great news !
Thanks for your great work.
