### ISSUE TITLE
libGL error

### ISSUE THREAD

**Issue by hubitor** [Mindmapp/mindmapp#46]
I'm getting after:
```
$ chmod a+x Mindmapp-0.7.12.appimage
$ ./Mindmapp-0.7.12.appimage
```

these errors:
```
libGL error: pci id for fd 11: 80ee:beef, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
[10:18:47.400] [info] Checking for update
```
on a VM with Antergos although Mindmapp seems to be working normally.

**Comment by cedoor** [comment]
Hi @hubitor,

can you check if it gives this error with other .appImage applications built with electron-builder?
Do you see this error on physical machine with Antergos and not on VM?

**Comment by hubitor** [comment]
Hi @cedoor,

> can you check if it gives this error with other .appImage applications built with electron-builder?

Just checked with Mindomo_v.8.0.40_x64.AppImage (I assume is built with electron-builder) and there is not such an error.

> Do you see this error on physical machine with Antergos and not on VM?

I have installed Mindmapp on an Antergos-VM. I saw this error in the console after I run:
` $ ./Mindmapp-0.7.12.appimage
`but otherwise Mindmapp seems to  be working normally.

**Comment by cedoor** [comment]
Hi @hubitor,

umh, I don't know if Mindomo use electron-builder, but I think the problem is caused by VM software. Are you using Virtualbox?

**Comment by hubitor** [comment]
Hi @cedoor ,

> Are you using Virtualbox?

Yes.

**Comment by cedoor** [comment]
Hi @hubitor,

are you installed the Virtualbox Guest Additions?

**Comment by hubitor** [comment]
Hi @cedoor ,
> are you installed the Virtualbox Guest Additions?

Yes.
```
$ pacman -Q | grep virtualbox-guest-dkms
virtualbox-guest-dkms 5.2.18-1
```

**Comment by hubitor** [comment]
Hi @cedoor ,

I see now that I get a similar error when I open a text file with kate. So it's not mindmapp.

**Comment by cedoor** [comment]
Hi @hubitor, 

thank you!
