### ISSUE TITLE
Menu text & icons rendering issue

### ISSUE THREAD

**Issue by hubitor** [Mindmapp/mindmapp#47]
I have installed Mindmapp both on my main system with Arch Linux as well on a VM with Antergos. On Arch the menu text and icons are not rendered normally:
![mindmapp_screenshot_20180811_170927](https://user-images.githubusercontent.com/6114541/44452327-88c5c380-a5f6-11e8-8561-a1eebe2071ca.png)

On the VM with Antergos Mindmapp there is not such issue. 
it seems to be related with electron since I'm having similar issue with Pencil:
[Pencil issue](https://github.com/evolus/pencil/issues/511)

**Comment by cedoor** [comment]
Hi @hubitor,

I'm reading this vscode [issue](https://github.com/Microsoft/vscode/issues/55934). I believe the error is caused by glibc in your downgraded version. We await further developments from Electron or Arch Linux in this days.

**Comment by cedoor** [comment]
I updated Electron version to [2.0.8](https://github.com/electron/electron/releases/tag/v2.0.8), can you check if with the latest glibc version the next version of Mindmapp crashes? The new 0.7.14 version will soon be released.

**Comment by hubitor** [comment]
Hi @cedoor ,

glibc seems to be already the latest version:

```
$ pacman -Q | grep glibc 
glibc 2.28-4
lib32-glibc 2.28-4
```

I have just tried Mindmapp-0.7.13.AppImage and I still have the issue.

**Comment by cedoor** [comment]
I release the new version now. Try [it](https://github.com/Mindmapp/mindmapp/releases/tag/v0.7.14).

**Comment by hubitor** [comment]
Just tried Mindmapp-0.7.14.AppImage . The same...
Besides that I also see this:

`Gtk-Message: 14:13:32.681: GtkDialog mapped without a transient parent. This is discouraged.
`

**Comment by minthemiddle** [comment]
I solved my problems with inproper display by deletin Material Design (!) icon fonts. See[here](https://github.com/electron/electron/issues/14643#issuecomment-423101551)
