### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by jcmljunior** [Mindmapp/mindmapp#52]
Hi @cedoor, good afternoon.
I would like to know if you have an interest in translating the mindmap into Portuguese? maybe I can help you.

**Comment by cedoor** [comment]
Hi @jcmljunior,

Yes, of course! If you know Portuguese you can send me a pull request as [this](https://github.com/Mindmapp/mindmapp/pull/30/files)! If you need help write me!

**Comment by jcmljunior** [comment]
![screenshot_20180905_201233](https://user-images.githubusercontent.com/35886100/45126150-44830900-b148-11e8-98d7-378278eb7ade.png)
Soon everything will be ready... :)

**Comment by jcmljunior** [comment]
Hi @cedoor, I need a permission to send all files modified...
![screenshot_20180905_211216](https://user-images.githubusercontent.com/35886100/45127860-dabb2d00-b150-11e8-887c-19d0d07f03a7.png)

**Comment by cedoor** [comment]
Hi @jcmljunior,

you should work on a forked repository, then you should send me the pull request. Make the same changes on a forked Mindmapp repository, commit and push all on Github.

**Comment by jcmljunior** [comment]
I understand, thanks for the tip.
