### ISSUE TITLE
Stuck at chunk on run

### ISSUE THREAD

**Issue by OrganicChem** [Mindmapp/mindmapp#55]
I get stuck at:
chunk {vendor} vendor.js, vendor.js.map (vendor) 8.01 MB [initial] [rendered]

after issuing npm run ng:build #

**Comment by cedoor** [comment]
Hi @OrganicChem,

can you check if you have the last version of npm and node?

**Comment by OrganicChem** [comment]
I have node 10.10.0 and npm 6.4.1

**Comment by cedoor** [comment]
I tried with the same versions and it works.
Have you tried a clean environment? After cleaning up cache and removing `node_modules` folder?
Look at this [issue](https://github.com/angular/angular-cli/issues/11747) too and see if it solves something.

**Comment by OrganicChem** [comment]
I ran npm cache clean --force, the cloned the project again and after ng:build:
![screen shot 2018-09-14 at 11 35 08 am](https://user-images.githubusercontent.com/3411037/45560162-57fe3600-b812-11e8-98e2-5485b6452171.png)
