### ISSUE TITLE
ctrl+backspace and ctrl+delete shortcuts

### ISSUE THREAD

**Issue by safield** [Mindmapp/mindmapp#56]
While in the context of text editing, the following expected keyboard shortcuts are not working...

ctrl+backspace - delete word to left of caret
ctrl+delete - delete work to right of caret.

The similar shortcut of ctrl+shift+[left/right], is working correctly to select word to left or right of caret respectively.

**Comment by cedoor** [comment]
Hi @safield,

thank you for the reporting, this is a `mmp` library problem. I move the issue in the `mmp` project.
