### ISSUE TITLE
Low quality icon

### ISSUE THREAD

**Issue by tiotrom** [Mindmapp/mindmapp#61]
Great app btw! Thank you!
In Manjaro Gnome, installed from AUR, the icon image is very low quality https://aur.archlinux.org/packages/mindmapp/#news - any idea why?

![2019-02-02_19-28](https://user-images.githubusercontent.com/34804533/52167803-36e6a500-2721-11e9-9c18-026dc452c34b.png)

**Comment by cedoor** [comment]
I also tried the .deb format and the icon is good, maybe it is necessary to correctly set some parameters of the AUR package.
