### ISSUE TITLE
Improved Shortcuts

### ISSUE THREAD

**Issue by stefnotch** [Mindmapp/mindmapp#68]
In my opinion, the current shortcuts could be improved a little bit.

**My suggestions are**
- [ ] `Delete` to delete the current node. `CTRL + X` already cuts the current node, so being able to delete the node would make sense.
- [ ] `CTRL + S` during text editing to save the mindmap.

**Comment by cedoor** [comment]
Hi @stefnotch,
there is already a shortcut the current node: `ALT + -`. While for the second point, it is necessary to fix the mmp library, I add the task! 

Thank you.
