### ISSUE TITLE
Tab Key

### ISSUE THREAD

**Issue by stefnotch** [Mindmapp/mindmapp#70]
While editing a node, the tab key can be used to jump to a (seemingly random) different node. I'd recommend disabling the tab key or fixing it's behaviour, as it's currently rather buggy.

Video: 
![20190513_164106](https://user-images.githubusercontent.com/10220080/57630627-3ff7d580-759e-11e9-8654-78ad4314e7b3.gif)

**Comment by cedoor** [comment]
Hi @stefnotch ,

thank you so much!

**Comment by cedoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tab key on the nodes](https://trello.com/c/ojK6iteZ/1-tab-key-on-the-nodes)
