### ISSUE TITLE
failed to export image

### ISSUE THREAD

**Issue by jcmljunior** [Mindmapp/mindmapp#73]
Sistema: Windows 8.1
**Nota:** The error does not happen when I write numbers.

![Screenshot_2](https://user-images.githubusercontent.com/35886100/63619241-7513bb00-c5c4-11e9-877b-987ec2c648f3.png)

![Screenshot_1](https://user-images.githubusercontent.com/35886100/63619126-2ebe5c00-c5c4-11e9-8d49-7cd1c8e2c819.png)

**Comment by jcmljunior** [comment]
The same problem is being presented when I try to save the project.
![image](https://user-images.githubusercontent.com/35886100/63620733-7cd55e80-c5c8-11e9-9fa1-6e49aad4e8cf.png)

**Comment by cedoor** [comment]
Hi Júlio, with the new version this problem will no longer exist, Electron will be replaced with browser PWA!
